---
application:
  name: "dbdmwp"
  project: "dbdmwp"
  organization: "QoveryCommunity"
  publicly_accessible: true
  port: 80
  storage:
  - name: "uploads"
    size: "20"
    type: "ssd"
    mount_point: "/var/www/html/wp-content/uploads"
databases:
- type: "MYSQL"
  name: "wordpress"
  version: "8.0"
routers:
- name: "main-ux221rhildred"
  routes:
  - application_name: "dbdmwp"
    paths:
    - "/*"
